python train_synthetic.py --problem rank1 --model share_fc
python train_synthetic.py --problem rank2 --model share_fc
python train_synthetic.py --problem rank5 --model share_fc
python train_synthetic.py --problem 2d_rot8 --model share_fc
python train_synthetic.py --problem 2d_rot8_flip --model share_fc
python train_synthetic.py --problem 2d_rot8 --model share_conv
python train_synthetic.py --problem 2d_rot8_flip --model share_conv
python train_synthetic.py --problem rank1 --model share_conv
python train_synthetic.py --problem rank2 --model share_conv
python train_synthetic.py --problem rank5 --model share_conv